name: Run Flask Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.10"  # Atualize para a versão desejada do Python
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask flask-cors Werkzeug gunicorn openpyxl python-dateutil pytz loguru
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Flask server
      env:
        FLASK_APP: app.py  # Substitua pelo nome do arquivo principal do Flask
        FLASK_ENV: development
      run: |
        python -m flask run --host=0.0.0.0 --port=5000
